# Generated by Django 3.0.7 on 2020-06-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_extra_cheese'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_image',
            field=models.CharField(default='abc', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='food_name',
            field=models.CharField(max_length=100),
        ),
    ]
