# Generated by Django 3.0.7 on 2020-06-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200625_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
