# Generated by Django 3.0.7 on 2020-06-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_fooditem_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Menu',
        ),
    ]
