# Generated by Django 3.0.7 on 2020-07-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200705_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
