# Generated by Django 3.0.7 on 2021-07-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='orders.Transaction'),
            preserve_default=False,
        ),
    ]
